Confirmation:
    CoExpression:
        Input:
            dataName_bic: src/python/robinviz/databases/inputtrees/geodata/YEAST1_2993_173.txt
            dataName2_bic: src/python/robinviz/databases/inputtrees/geodata/YEAST1_2993_173.txt
            ppifilename_bic: src/python/robinviz/databases/inputtrees/ppidata/ppi.txt
            catfile_bic: sources/organisms/Yeast2993x173/category.txt
            gofile_bic: src/python/robinviz/databases/inputtrees/assocdata/go_slim.txt
        Drawing:
            minBicSize: 1
            maxBicSize: 5000
            width: 15
            space: 50
            increment: 300
            removeRat: 0.0
            nodeSize: 50.0
            edgeBendImp: 35.0
            colorScale: 130.0
            edgThicknessTher: 4.0
        Biclustering:
            biclustering: 4
            bimax_low_dim1: 100
            bimax_low_dim2: 7
            ther_disc: 0.1
            bic_num_bimax: 100
            bic_num_cc: 50
            maxScore_: 10
            minHeight_: 500
            minWidth_: 5
            maxSizeSubMatrix_exp1_g: 200
            maxSizeSubMatrix_exp1_c: 26
            minSizeSubMatrix_exp1_g: 100
            minSizeSubMatrix_exp1_c: 20
            repeat: 50
            hvaluemin: 10.0
            increment_exp1_g: 50
            increment_exp1_c: 2
        Algorithms:
            ownFlag: 0
            lebFlag: 0
            ccFlag: 0
            msbeFlag: 0
            bimaxFlag: 0
            rlebFlag: 1
            brandFlag: 1
            brandFlag2: 0
            ourMethodFlag: 0
            ledaPostFlag: 0
            readOption: 1
            ffd_layout: 0
            layered_layout: 1
            circular_layout: 0
            circular_ffd_layout: 0
            go_info: 1
            edgesBetween: 1
            sharedGenes: 0
            hvalueWeighting: 1
            enrichmentWeighting_o: 0
            enrichmentWeighting_f: 0
            ppihitratioWeighting: 0
            is_ppi_directed: 0
            
    CoFunctionality:
        Input:
            ppifilename_go: src/python/robinviz/databases/inputtrees/ppidata/ppi.txt
            catfile_go: sources/organisms/Yeast2993x173/category.txt
            gofile_go: src/python/robinviz/databases/inputtrees/assocdata/go_slim.txt
            dataName_go: src/python/robinviz/databases/inputtrees/assocdata/input_go.txt
        Drawing:
            removeRat: 0.01
            nodeSize: 50.0
            edgeBendImp: 35.0
            colorScale: 130.0
            edgThicknessTher: 4.0
        Algorithms:
            go_info: 0
            edgesBetween: 1
            sharedGenes: 0
